name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io   
        with:
          args: >
            -Dsonar.organization=chethanmk842-beep
            -Dsonar.projectKey=chethanmk842-beep_Devops-Internship
